// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyAsiMDq_yrdu6qUMYpu6vqoEKDUV_jVvDo',
    appId: '1:896712593730:web:cb8843198084e738b9f8db',
    messagingSenderId: '896712593730',
    projectId: 'shatranj-f2744',
    authDomain: 'shatranj-f2744.firebaseapp.com',
    storageBucket: 'shatranj-f2744.firebasestorage.app',
    measurementId: 'G-TZ9LRK7TY0',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyCUG9tF1M1LnuvoGl0H9BbSxuFBlMWWTUs',
    appId: '1:896712593730:android:4cb73bf1fb4fb98cb9f8db',
    messagingSenderId: '896712593730',
    projectId: 'shatranj-f2744',
    storageBucket: 'shatranj-f2744.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyBMQSnWXpIuOBcEh4lS8S8Blratp0Z-QII',
    appId: '1:896712593730:ios:daba77f5b580783fb9f8db',
    messagingSenderId: '896712593730',
    projectId: 'shatranj-f2744',
    storageBucket: 'shatranj-f2744.firebasestorage.app',
    iosBundleId: 'com.ictinus.shatranj',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyBMQSnWXpIuOBcEh4lS8S8Blratp0Z-QII',
    appId: '1:896712593730:ios:daba77f5b580783fb9f8db',
    messagingSenderId: '896712593730',
    projectId: 'shatranj-f2744',
    storageBucket: 'shatranj-f2744.firebasestorage.app',
    iosBundleId: 'com.ictinus.shatranj',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyAsiMDq_yrdu6qUMYpu6vqoEKDUV_jVvDo',
    appId: '1:896712593730:web:563a42ce2f751077b9f8db',
    messagingSenderId: '896712593730',
    projectId: 'shatranj-f2744',
    authDomain: 'shatranj-f2744.firebaseapp.com',
    storageBucket: 'shatranj-f2744.firebasestorage.app',
    measurementId: 'G-8RTM48VL8F',
  );
}
